{{ if .Values.pvEnabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.namespace }}-{{ .Values.appName }}-data-pv"
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Values.namespace }}
    name: {{ .Values.pvcName }}
  hostPath:
    path: /data
{{ end }}